version: "3"
networks:
  internal:
services:

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379
    networks:
      - internal


  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - internal
  


